import { contextFor } from "@yaebal/contexts";
import { Bot } from "@yaebal/core";
import { html } from "@yaebal/fmt";
import type { InlineQueryResult } from "@yaebal/types";

const token = process.env.BOT_TOKEN;
if (!token) {
	console.error("set BOT_TOKEN in examples/inline-search/.env first (copy .env.example)");
	process.exit(1);
}

const bot = new Bot(token, { allowedUpdates: ["message", "inline_query", "chosen_inline_result"] })
	.command("start", (ctx) =>
		ctx.send(html`<b>inline search</b>\nopen any chat and type <code>@your_bot query</code>.`),
	)
	.on("inline_query", async (ctx) => {
		// bare core has no per-update contexts — @yaebal/contexts is a separate install on
		// top of it. wrap the raw update once and the generated shortcuts appear:
		// .answer() fills inline_query_id itself, payload fields are typed.
		const inline = contextFor("inline_query", ctx.api, ctx.update);

		const query = inline.query.trim() || "yaebal";
		const offset = Number(inline.offset || 0);
		const results = Array.from({ length: 5 }, (_, index): InlineQueryResult => {
			const id = offset + index + 1;
			const title = `${query} result ${id}`;

			return {
				type: "article",
				id: String(id),
				title,
				description: "generated by examples/inline-search",
				input_message_content: {
					message_text: `inline result: ${title}`,
				},
			};
		});

		await inline.answer(results, {
			cache_time: 0,
			is_personal: true,
			next_offset: String(offset + results.length),
			button: { text: "open bot", start_parameter: "inline" },
		});
	})
	.on("chosen_inline_result", (ctx) => {
		const chosen = contextFor("chosen_inline_result", ctx.api, ctx.update);

		console.log("chosen inline result", {
			resultId: chosen.result_id,
			from: chosen.senderId,
			query: chosen.query,
		});
	})
	.onStart((info) => console.log(`@${info.username} inline search is live`));

process.once("SIGINT", () => bot.stop());
process.once("SIGTERM", () => bot.stop());

await bot.start();
