import { FileId } from "@yaebal/file-id";
import { files } from "@yaebal/files";
import { mediaCache } from "@yaebal/media-cache";
import { mediaGroup } from "@yaebal/media-group";
import { renderChat } from "@yaebal/preview";
import { splitter } from "@yaebal/split";
import { bold, createBot, format, media } from "yaebal";

const token = process.env.BOT_TOKEN;
if (!token) {
	console.error("set BOT_TOKEN in examples/media-studio/.env first (copy .env.example)");
	process.exit(1);
}

const cache = mediaCache();

const bot = createBot(token)
	.install(files())
	.install(cache.plugin())
	.install(splitter(900))
	.install(
		mediaGroup(
			async (ctx, messages) => {
				const photoCount = messages.filter((message) => message.photo).length;
				const videoCount = messages.filter((message) => message.video).length;
				await ctx.reply(
					`album captured: ${messages.length} item(s), ${photoCount} photo(s), ${videoCount} video(s).`,
				);
			},
			{
				// albums flush from a timer, outside bot.onError's reach — handle failures here
				onError: (error) => console.error("album handler failed:", error),
			},
		),
	);

bot
	.command("start", (ctx) =>
		ctx.reply(
			[
				"media studio is ready.",
				"try /poster, /cache, /preview, /long, /story.",
				"send a document to get a file link, or send an album to see media-group batching.",
			].join("\n"),
		),
	)
	.command("poster", (ctx) =>
		ctx.sendPhoto(media.url("https://picsum.photos/seed/yaebal-media-studio/900/600"), {
			caption: "remote photo via core media.url",
		}),
	)
	.command("cache", async (ctx) => {
		await cache.photo(
			ctx,
			"poster:v1",
			media.url("https://picsum.photos/seed/yaebal-cache/900/600"),
			{
				caption: "manual mode: file_id cached under the key poster:v1",
			},
		);
		await ctx.sendPhoto(media.url("https://picsum.photos/seed/yaebal-cache/900/600"), {
			caption: "transparent mode: same url, so the cached file_id is reused — no re-upload",
		});
	})
	.command("preview", (ctx) => {
		// a tour of @yaebal/preview's flagship features: reply quotes, forwarded headers,
		// reactions, a link-preview card, per-message avatars, message grouping (these two
		// "yaebal" messages render as one visual group — one avatar, one name label), and a
		// fully custom palette layered on top of the dark theme.
		const svg = renderChat(
			[
				{ from: "bot", name: "yaebal", text: "media studio preview", time: "13:36" },
				{ from: "user", text: "/poster", time: "13:37", status: "read" },
				{
					from: "bot",
					name: "yaebal",
					forward: { from: "release notes" },
					text: "media studio now speaks reply quotes, reactions, and link previews.",
					time: "13:37",
				},
				{
					// same sender + name as the previous message — groups with it (shared avatar,
					// no repeated name label)
					from: "bot",
					name: "yaebal",
					reply: { name: "yaebal", text: "media studio now speaks reply quotes..." },
					text: "here is a generated telegram-style svg.",
					time: "13:37",
					reactions: [{ emoji: "🔥", count: 3, chosen: true }],
					buttons: [["cache", "album"], ["files"]],
				},
				{
					from: "bot",
					avatar: "📚",
					name: "docs bot",
					text: "full api + every media type, live:",
					webpage: {
						site: "yaebal.mom",
						title: "@yaebal/preview",
						description: "render a telegram-style chat to an svg string — zero deps, zero runtime.",
					},
					time: "13:38",
				},
			],
			{ theme: "dark", palette: { out: "#204020" } },
		);

		return ctx.sendDocument(
			media.buffer(new TextEncoder().encode(svg), "media-studio-preview.svg"),
			{
				caption: "generated by @yaebal/preview",
			},
		);
	})
	.command("long", (ctx) => {
		const report = Array.from(
			{ length: 80 },
			(_, index) =>
				`line ${index + 1}: media job shard ${index % 7} ok, cache warm, album queue clear.`,
		).join("\n");

		// the bold heading survives the split — entities are clipped per part
		return ctx.replyLong(format`${bold("nightly media report")}\n${report}`, undefined, {
			delayMs: 250,
		});
	})
	.command("story", (ctx) => {
		const description = Array.from(
			{ length: 30 },
			(_, index) => `chapter ${index + 1}: the pipeline hums, the cache never misses.`,
		).join("\n");

		// caption strategy: first part becomes the photo caption, the rest are messages
		return ctx.sendPhotoLong(
			media.url("https://picsum.photos/seed/yaebal-story/900/600"),
			format`${bold("studio story")}\n${description}`,
		);
	})
	.on("message:document", async (ctx) => {
		if (!ctx.document) return;

		// one getFile, memoized on the handle: metadata first, url after
		const dl = ctx.files.download(ctx.document);
		const info = await dl.info();
		const url = await dl.url();

		return ctx.reply(
			[
				`document: ${info.file_size ?? "?"} byte(s), unique id ${info.file_unique_id}.`,
				"link resolved. do not leak this url:",
				url,
			].join("\n"),
		);
	})
	.on("message:photo", async (ctx) => {
		const largest = ctx.photo?.at(-1);
		if (!ctx.photo || !largest) return;

		// PhotoSize[] goes in as-is — the largest size is picked automatically
		const url = await ctx.files.url(ctx.photo);
		// @yaebal/file-id looks *inside* the id — no api call involved
		const parsed = FileId.from(largest.file_id);

		return ctx.reply(
			`largest photo lives on DC ${parsed.dcId} (${parsed.kind}, format v${parsed.version}).\n${url}`,
		);
	})
	.onStart(async (info) => {
		await bot.api
			.call("setMyCommands", {
				commands: [
					{ command: "start", description: "show media studio" },
					{ command: "poster", description: "send remote photo" },
					{ command: "cache", description: "show media cache" },
					{ command: "preview", description: "send svg preview" },
					{ command: "long", description: "split a long report" },
					{ command: "story", description: "long caption via sendPhotoLong" },
				],
			})
			.catch(() => {});
		console.log(`@${info.username} media studio is live`);
	});

process.once("SIGINT", () => bot.stop());
process.once("SIGTERM", () => bot.stop());

await bot.start();
