import { Bot, media } from "@yaebal/core";
import { files } from "@yaebal/files";
import { mediaCache } from "@yaebal/media-cache";
import { mediaGroup } from "@yaebal/media-group";
import { renderChat } from "@yaebal/preview";
import { splitter } from "@yaebal/split";

const token = process.env.BOT_TOKEN;
if (!token) {
	console.error("set BOT_TOKEN in examples/media-studio/.env first (copy .env.example)");
	process.exit(1);
}

const cache = mediaCache();

const bot = new Bot(token)
	.install(files())
	.install(splitter(900))
	.install(
		mediaGroup(async (ctx, messages) => {
			const photoCount = messages.filter((message) => message.photo).length;
			const videoCount = messages.filter((message) => message.video).length;
			await ctx.reply(
				`album captured: ${messages.length} item(s), ${photoCount} photo(s), ${videoCount} video(s).`,
			);
		}),
	);

cache.hook(bot.api);

bot
	.command("start", (ctx) =>
		ctx.reply(
			[
				"media studio is ready.",
				"try /poster, /cache, /preview, /long.",
				"send a document to get a file link, or send an album to see media-group batching.",
			].join("\n"),
		),
	)
	.command("poster", (ctx) =>
		ctx.sendPhoto(media.url("https://picsum.photos/seed/yaebal-media-studio/900/600"), {
			caption: "remote photo via core media.url",
		}),
	)
	.command("cache", async (ctx) => {
		await cache.photo(
			ctx,
			"poster:v1",
			media.url("https://picsum.photos/seed/yaebal-cache/900/600"),
			{
				caption: "first call may upload/fetch; cache stores file_id after telegram responds",
			},
		);
		await ctx.sendPhoto(cache.media.url("https://picsum.photos/seed/yaebal-cache/900/600"), {
			caption: "second call can transparently reuse cached file_id",
		});
	})
	.command("preview", (ctx) => {
		const svg = renderChat(
			[
				{ from: "bot", name: "yaebal", text: "media studio preview", time: "13:36" },
				{ from: "user", text: "/poster", time: "13:37", status: "read" },
				{
					from: "bot",
					name: "yaebal",
					text: "here is a generated telegram-style svg.",
					time: "13:37",
					buttons: [["cache", "album"], ["files"]],
				},
			],
			{ theme: "dark" },
		);

		return ctx.sendDocument(
			media.buffer(new TextEncoder().encode(svg), "media-studio-preview.svg"),
			{
				caption: "generated by @yaebal/preview",
			},
		);
	})
	.command("long", (ctx) => {
		const report = Array.from(
			{ length: 80 },
			(_, index) =>
				`line ${index + 1}: media job shard ${index % 7} ok, cache warm, album queue clear.`,
		).join("\n");

		return ctx.replyLong(report);
	})
	.on("message:document", async (ctx) => {
		const fileId = ctx.message?.document?.file_id;
		if (!fileId) return;

		const url = await ctx.files.fileLink(fileId);
		return ctx.reply(`document link resolved. do not leak this url:\n${url}`);
	})
	.on("message:photo", async (ctx) => {
		const fileId = ctx.message?.photo?.at(-1)?.file_id;
		if (!fileId) return;

		const url = await ctx.files.fileLink(fileId);
		return ctx.reply(`largest photo file link resolved:\n${url}`);
	})
	.onStart(async (info) => {
		await bot.api
			.call("setMyCommands", {
				commands: [
					{ command: "start", description: "show media studio" },
					{ command: "poster", description: "send remote photo" },
					{ command: "cache", description: "show media cache" },
					{ command: "preview", description: "send svg preview" },
					{ command: "long", description: "split a long report" },
				],
			})
			.catch(() => {});
		console.log(`@${info.username} media studio is live`);
	});

process.once("SIGINT", () => bot.stop());
process.once("SIGTERM", () => bot.stop());

await bot.start();
