<script lang="ts">
	import Code from "$lib/Code.svelte";

	const answer = `bot.on("inline_query", async (ctx) => {
  const query = ctx.update.inline_query!;
  const results = await search(query.query);

  await ctx.api.call("answerInlineQuery", {
    inline_query_id: query.id,
    cache_time: 10,
    is_personal: true,
    results: results.map((item) => ({
      type: "article",
      id: item.id,
      title: item.title,
      input_message_content: { message_text: item.text },
    })),
  });
});`;

	const chosen = `bot.on("chosen_inline_result", async (ctx) => {
  const chosen = ctx.update.chosen_inline_result!;
  await analytics.track("inline_chosen", {
    resultId: chosen.result_id,
    userId: chosen.from.id,
    query: chosen.query,
  });
});`;

	const keyboard = `new InlineKeyboard()
  .switchInline("share", "product:42")
  .row()
  .switchInlineCurrentChat("search here", "cats");`;
</script>

<svelte:head>
	<title>inline mode — yaebal</title>
</svelte:head>

<h1>inline mode</h1>
<p class="lead">
	let users type <code>@your_bot query</code> in any chat and pick a result generated by your bot.
</p>

<h2>answer inline queries</h2>
<p>
	inline query handlers must answer with a list of results. keep the response fast, cache where
	possible, and use <code>is_personal</code> when results depend on the current user.
</p>
<Code code={answer} title="inline-query.ts" />

<h2>track chosen results</h2>
<p>
	if enabled in botfather, telegram sends <code>chosen_inline_result</code> after a user picks one of
	your results. use it for analytics, not for critical business logic.
</p>
<Code code={chosen} title="chosen-result.ts" />

<h2>switch inline buttons</h2>
<p>
	inline keyboard buttons can open the inline picker with a prefilled query. this is useful for
	sharing products, documents, search results, or mini app content.
</p>
<Code code={keyboard} title="keyboard.ts" />

<h2>rules of thumb</h2>
<ul>
	<li>return stable result ids so analytics and caches stay meaningful.</li>
	<li>keep result payloads small; the user is waiting inside telegram's inline picker.</li>
	<li>use <code>cache_time</code> aggressively for public search results.</li>
	<li>set <code>is_personal</code> for private/user-specific results.</li>
	<li>add <code>inline_query</code> and <code>chosen_inline_result</code> to <code>allowedUpdates</code> when polling.</li>
</ul>
