<script lang="ts">
	import Code from "$lib/Code.svelte";

	const answer = `import { createBot } from "yaebal";

const search = async (query: string) => [{ id: "1", title: "result", text: "text" }];
const bot = createBot(process.env.BOT_TOKEN!);

bot.on("inline_query", async (ctx) => {
  const results = await search(ctx.query);

  await ctx.answer(
    results.map((item) => ({
      type: "article" as const,
      id: item.id,
      title: item.title,
      input_message_content: { message_text: item.text },
    })),
    { cache_time: 10, is_personal: true },
  );
});`;

	const builderSnippet = `import { createBot } from "yaebal";
import { InlineQueryResult, InputMessageContent } from "@yaebal/inline-results";

const search = async (query: string) => [{ id: "1", title: "result", url: "https://example.com" }];
const bot = createBot(process.env.BOT_TOKEN!);

bot.on("inline_query", async (ctx) => {
  const items = await search(ctx.query);

  await ctx.answer(
    items.map((item) =>
      InlineQueryResult.article(item.id, item.title, InputMessageContent.text(item.url)),
    ),
    { cache_time: 10 },
  );
});`;

	const chosen = `import { createBot } from "yaebal";

declare const analytics: { track(event: string, props: Record<string, unknown>): Promise<void> };
const bot = createBot(process.env.BOT_TOKEN!);

bot.on("chosen_inline_result", async (ctx) => {
  await analytics.track("inline_chosen", {
    resultId: ctx.result_id,
    userId: ctx.from.id,
    query: ctx.query,
  });
});`;

	const keyboard = `import { InlineKeyboard } from "yaebal";

new InlineKeyboard()
  .switchInline("share", "product:42")
  .row()
  .switchInlineCurrentChat("search here", "cats")
  .build();`;
</script>

<svelte:head>
	<title>inline mode — yaebal</title>
</svelte:head>

<h1>inline mode</h1>
<p class="lead">
	let users type <code>@your_bot query</code> in any chat and pick a result generated by your bot.
</p>

<h2>answer inline queries</h2>
<p>
	inline query handlers must answer with a list of results. keep the response fast, cache where
	possible, and use <code>is_personal</code> when results depend on the current user.
	<code>ctx.answer()</code> takes the results array positionally, plus an options object for
	<code>cache_time</code>/<code>is_personal</code>/<code>next_offset</code>.
</p>
<Code code={answer} title="inline-query.ts" />

<h2>build results without hand-rolled objects</h2>
<p>
	<a href="/docs/plugins/inline-results/">@yaebal/inline-results</a> ships one typed factory per
	<code>InlineQueryResult</code>/<code>InputMessageContent</code> variant — required fields are
	positional, everything else is a trailing options object, so a result reads as data instead of
	an object literal that can silently drift from the schema.
</p>
<Code code={builderSnippet} title="inline-query-builder.ts" />

<h2>track chosen results</h2>
<p>
	if enabled in botfather, telegram sends <code>chosen_inline_result</code> after a user picks one of
	your results. use it for analytics, not for critical business logic.
</p>
<Code code={chosen} title="chosen-result.ts" />

<h2>switch inline buttons</h2>
<p>
	inline keyboard buttons can open the inline picker with a prefilled query. this is useful for
	sharing products, documents, search results, or mini app content.
</p>
<Code code={keyboard} title="keyboard.ts" />

<h2>rules of thumb</h2>
<ul>
	<li>return stable result ids so analytics and caches stay meaningful.</li>
	<li>keep result payloads small; the user is waiting inside telegram's inline picker.</li>
	<li>use <code>cache_time</code> aggressively for public search results.</li>
	<li>set <code>is_personal</code> for private/user-specific results.</li>
	<li>add <code>inline_query</code> and <code>chosen_inline_result</code> to <code>allowedUpdates</code> when polling.</li>
</ul>
