<script lang="ts">
	import Code from "$lib/Code.svelte";
	import CodeTabs from "$lib/CodeTabs.svelte";
	import Try from "$lib/Try.svelte";

	const scaffoldTabs = [
		{ label: "docker", code: "pnpm create yaebal my-bot --deploy docker" },
		{ label: "compose", code: "pnpm create yaebal my-bot --deploy compose" },
		{ label: "fly", code: "pnpm create yaebal my-bot --deploy fly" },
		{ label: "railway", code: "pnpm create yaebal my-bot --deploy railway" },
		{ label: "cloudflare", code: "pnpm create yaebal my-bot --deploy cloudflare" },
		{ label: "vercel", code: "pnpm create yaebal my-bot --deploy vercel" },
	];

	const dockerfile = `# generated by \`create-yaebal --deploy docker\` (node runtime shown; bun/deno differ)
FROM node:22-alpine
WORKDIR /app

COPY package.json package-lock.json* pnpm-lock.yaml* yarn.lock* ./
RUN if [ -f pnpm-lock.yaml ]; then corepack enable && pnpm install --prod --frozen-lockfile; \\
	elif [ -f yarn.lock ]; then corepack enable && yarn install --production --frozen-lockfile; \\
	else npm install --omit=dev; fi

COPY . .

ENV NODE_ENV=production
CMD ["node", "--experimental-strip-types", "src/index.ts"]`;

	const composeYaml = `# create-yaebal --deploy compose adds this next to the same Dockerfile
services:
  my-bot:
    build: .
    env_file: .env
    restart: unless-stopped`;

	const systemd = `[Unit]
Description=yaebal bot
After=network-online.target

[Service]
WorkingDirectory=/srv/my-bot
EnvironmentFile=/srv/my-bot/.env
ExecStart=/usr/bin/node --experimental-strip-types src/index.ts
Restart=always
RestartSec=5
User=yaebal

[Install]
WantedBy=multi-user.target`;

	const shutdown = `import { createBot } from "yaebal";

export const bot = createBot(process.env.BOT_TOKEN!);

bot.command("start", (ctx) => ctx.reply("hi"));

// docker, systemd and kubernetes all send SIGTERM before killing the process.
// bot.stop() lets the in-flight update finish and the current long-poll
// return before the process actually exits — an unhandled SIGTERM just
// kills mid-update.
process.once("SIGTERM", () => bot.stop());
process.once("SIGINT", () => bot.stop());

await bot.start();`;

	const cloudflareWorker = `import { createBot } from "yaebal";
import { cloudflareAdapter } from "@yaebal/web";

// wrangler.jsonc sets "compatibility_flags": ["nodejs_compat"], so — unlike a
// bare Workers fetch handler — process.env works at module scope here, the
// same as on every other runtime. no per-request env plumbing needed.
export const bot = createBot(process.env.BOT_TOKEN!);

bot.command("start", (ctx) => ctx.reply("hi from the edge"));

export default {
  fetch: cloudflareAdapter(bot, { secretToken: process.env.SECRET_TOKEN }),
};`;

	const vercelEdge = `// api/bot.ts — Vercel edge function
import { createBot, webhook } from "yaebal";

const bot = createBot(process.env.BOT_TOKEN!);
bot.command("start", (ctx) => ctx.reply("hi from the edge"));

export const config = { runtime: "edge" };
export default webhook(bot, { secretToken: process.env.SECRET_TOKEN });`;

	const targets = [
		{ label: "docker", code: "docker build -t my-bot .\ndocker run --env-file .env my-bot" },
		{ label: "systemd", code: "sudo systemctl enable --now my-bot\nsudo journalctl -u my-bot -f" },
		{ label: "fly", code: "fly launch\nfly secrets set BOT_TOKEN=... WEBHOOK_SECRET=...\nfly deploy" },
		{ label: "railway", code: "railway init\nrailway variables set BOT_TOKEN=... WEBHOOK_SECRET=...\nrailway up" },
		{ label: "vercel", code: "vercel env add BOT_TOKEN\nvercel env add SECRET_TOKEN\nvercel deploy --prod" },
		{ label: "cloudflare", code: "wrangler secret put BOT_TOKEN\nwrangler secret put SECRET_TOKEN\nwrangler deploy" },
	];

	const catalog = [
		["none", "just the project — deploy it however you like", "—"],
		["docker", "Dockerfile + .dockerignore, single-stage, no build step", "polling"],
		["compose", "the same Dockerfile plus compose.yaml for local/vps runs", "polling"],
		["fly", "the same Dockerfile plus fly.toml", "polling"],
		["railway", "the same Dockerfile plus railway.json", "polling"],
		["cloudflare", "wrangler.jsonc (nodejs_compat on) + a cloudflareAdapter bootstrap", "webhook"],
		["vercel", "vercel.json + an api/bot.ts edge function", "webhook"],
	];
</script>

<svelte:head><title>deploy targets — yaebal</title></svelte:head>

<h1>deploy targets</h1>
<p class="lead">pick polling for containers and VPS, webhooks for serverless and edge.</p>

<h2>scaffold it</h2>
<p>
	<a href="/docs/scaffolding/">create-yaebal</a> generates the deploy files directly — the
	Dockerfile, compose/fly/railway config, or the edge function — matched to your chosen runtime.
	Skip the copy-pasting below and start from a working setup:
</p>
<CodeTabs tabs={scaffoldTabs} title="scaffold with a deploy target" />
<p>
	add <code>--ci</code> for a GitHub Actions workflow (install + typecheck on every push), or run
	the CLI with no flags for an interactive prompt that asks for all of this, including the deploy
	target.
</p>

<h2>deploy target catalog</h2>
<table>
	<thead><tr><th>target</th><th>generates</th><th>bot runs as</th></tr></thead>
	<tbody>
		{#each catalog as [name, generates, mode]}
			<tr><td><code>{name}</code></td><td>{generates}</td><td>{mode}</td></tr>
		{/each}
	</tbody>
</table>
<p>
	docker, compose, fly and railway all just run the Dockerfile's <code>CMD</code> — a
	long-polling process with no inbound HTTP to expose. cloudflare and vercel are serverless, so
	they get a webhook entry point instead; there's no persistent process to poll from.
</p>

<h2>docker</h2>
<p>
	the generated Dockerfile is single-stage on purpose — node's <code>--experimental-strip-types</code>
	runs <code>.ts</code> directly, so there's no build output to copy out of a separate builder
	stage. bun and deno get their own Dockerfile shape (<code>bun install</code> / <code>deno
	cache</code>); this is the node one.
</p>
<Code code={dockerfile} title="Dockerfile" lang="dockerfile" />
<div class="note">
	<strong>needs node ≥22.6.</strong> <code>--experimental-strip-types</code> is what lets the
	scaffolded project skip a build step. on an older node, add a build script and point
	<code>CMD</code> at the compiled output instead.
</div>
<CodeTabs tabs={[targets[0]]} title="run" />

<h2>docker compose</h2>
<p>use this over bare docker when you want one command to (re)start the bot alongside its env file.</p>
<Code code={composeYaml} title="compose.yaml" lang="yaml" />

<h2>systemd</h2>
<p>for a single VPS without containers, systemd gives restart, logs and simple secret loading.</p>
<Code code={systemd} title="my-bot.service" lang="ini" />
<CodeTabs tabs={[targets[1]]} title="run" />

<h2>graceful shutdown</h2>
<p>
	every target above can send <code>SIGTERM</code> before killing the process — docker on
	<code>stop</code>, systemd on restart, kubernetes before a pod eviction. without a handler, that
	SIGTERM kills the process mid long-poll or mid-update.
</p>
<Code code={shutdown} title="bot.ts" />

<h2>cloudflare workers</h2>
<p>
	create-yaebal's cloudflare target turns on wrangler's <code>nodejs_compat</code> flag, so
	<code>process.env</code> works at module scope exactly like it does on node — no per-request
	<code>env</code> plumbing. it wires <code>cloudflareAdapter</code> instead of the plain
	<code>webhook()</code> so an update that outlives the response (under a slow handler) still
	finishes via <code>ctx.waitUntil</code>.
</p>
<Code code={cloudflareWorker} title="src/index.ts" />
<CodeTabs tabs={[targets[5]]} title="deploy" />
<p>
	writing the worker by hand instead of scaffolding it? the bare-Workers pattern without
	<code>nodejs_compat</code> — building the bot inside <code>fetch(request, env)</code> — is on
	<a href="/docs/runtimes/#cloudflare-workers">runtime support</a>.
</p>

<h2>vercel</h2>
<p>
	the vercel target is a single edge function at <code>api/bot.ts</code>, no adapter needed —
	<code>webhook()</code> already returns a standard fetch handler.
</p>
<Code code={vercelEdge} title="api/bot.ts" />
<CodeTabs tabs={[targets[4]]} title="deploy" />
<Try id="webhook-ready" title="webhook.ts" />

<h2>fly.io and railway</h2>
<p>
	both reuse the same generated Dockerfile and run the bot in polling mode — <code>fly.toml</code>
	and <code>railway.json</code> just point the platform at it, with no inbound HTTP to configure.
</p>
<CodeTabs tabs={[targets[2], targets[3]]} title="deploy" />

<h2>target matrix</h2>
<table>
	<thead><tr><th>target</th><th>best mode</th><th>watch out for</th></tr></thead>
	<tbody>
		<tr><td>vps/systemd</td><td>polling or webhook</td><td>process restarts, logs, token rotation</td></tr>
		<tr><td>docker/fly/railway</td><td>polling</td><td>exactly one polling replica per token — a second one gets <code>409 conflict</code>, see <a href="/docs/troubleshooting/">troubleshooting</a></td></tr>
		<tr><td>vercel/cloudflare</td><td>webhook</td><td>no persistent filesystem, request timeout, cold starts</td></tr>
		<tr><td>kubernetes</td><td>webhook, or a single polling replica</td><td>leader election if you must poll from multiple pods; always handle <code>SIGTERM</code> for pod evictions</td></tr>
	</tbody>
</table>
<p>
	for concurrent polling that still needs exactly-once-per-chat-order semantics under real
	traffic, see <a href="/docs/runner/">@yaebal/runner</a> instead of scaling polling replicas
	horizontally.
</p>
